url: https://elena333.github.io
#baseurl: /wedding-template

# Site settings
title: Carmen y Rafael
email: helna.20.3@gmail.com
description: "Carmen y Rafa se casan"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty

include: ['_en_pages']