url: https://elena333.github.io
# baseurl: 

# Site settings
title: Carmen y Rafael
email: helna.20.3@gmail.com
description: "Carmen y Rafa se casan"

# Select place in Maps > Share > Embed a map > Copy HTML
google-maps-iframe: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3015.5526724458955!2d-5.1831060231586665!3d40.90362642586098!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd3f5c5e2f14cdd5%3A0x804936f85f33d84b!2sFinca%20el%20Ventorro!5e0!3m2!1sen!2sfr!4v1744136797065!5m2!1sen!2sfr" width="600" height="450" style="border:0;" allow="fullscreen" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'

# Build settings
markdown: kramdown
permalink: pretty

include: ['_en_pages']