url: https://elena333.github.io
# baseurl: 

# Site settings
title: Carmen y Rafael
email: helna.20.3@gmail.com
description: "Carmen y Rafa se casan"

# Select place in Maps > Share > Embed a map > Copy HTML
google-maps-iframe: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3018.8657595615446!2d-5.288015487336957!3d40.83091217125664!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd3f69dc5d5686b7%3A0x825ec676f4467994!2sIglesia%20Parroquial%20de%20Nuestra%20Se%C3%B1ora%20del%20Castillo!5e0!3m2!1sen!2snl!4v1746994458252!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'

# Build settings
markdown: kramdown
permalink: pretty

include: ['_en_pages']